blank_issues_enabled: false
contact_links:
    - name: ğŸ’¬ Discussions
      url: https://github.com/The-Terminal-Viet-Nam/frontend-homepage/discussions
      about: Ask questions and discuss
    - name: ğŸ¤ Contributing Guidelines
      url: https://github.com/The-Terminal-Viet-Nam/frontend-homepage/blob/main/CONTRIBUTING.md
      about: Please read through our contributing guidelines before creating an issue
    - name: ğŸ”’ Security Policy
      url: https://github.com/The-Terminal-Viet-Nam/frontend-homepage/security/policy
      about: Report security vulnerabilities
